### ISSUE TITLE
difference between nmap and noremap <Leader>y “+y

### ISSUE THREAD

**Issue by roachsinai** [kana/vim-fakeclip#28]
Thanks for this great plugin. I just want to know why setting `noremap <Leader>y “+y` in my .vimrc not work, when I press <kbd>;</kbd><kbd>yy</kbd>cannot copy current to Windows clipboard? But setting `nmap <Leader>y “+y` in my .vimrc works?

Why I change `noremap` to `nmap` is according your `fakeclip.txt`:

> 	modes	{lhs}		{rhs}					~
	-----	-----------	--------------------------------	~
	nv	"+y		<Plug>(fakeclip-y)

Does I have to specify the vim mode to Normal to use "+y (use nmap not map or noremap)?

**Comment by BlueDrink9** [comment]
If you look up `:h nnoremap` you'll see that it doesn't do recursive maps. When you use `nmap`, it maps to `"+y`, which then recursively maps to fakeclip's mapping.

**Comment by roachsinai** [comment]
Thanks for your reply! For my situation, `nmap <Leader>y "+y` works in WSL, `noremap <Leader>y "+y` works in Manjaro, finally.

**Comment by BlueDrink9** [comment]
The manjaro solution will be because the `"+`  register actually accesses the system clipboard. Either you're on neovim or `has('clipboard')==1`

**Comment by roachsinai** [comment]
@BlueDrink9 Yeah, on Manjaro I'm using gvim.
